server:
  port: 9090
spring:
  application:
    name: StockApp
  datasource:
    url: jdbc:mysql://localhost:3306/stockdb?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root@12345
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect